### ISSUE TITLE
Consider dropping global state

### ISSUE THREAD

**Issue by mikroskeem** [parkervcp/crocgodyl#1]
I think that crocgodyl's state should not be global, as this makes utilizing the library in projects which need to connect to multiple panels at the same time pretty much impossible out of the box.

**Comment by parkervcp** [comment]
I'll look into supporting instances of some sort for this.

**Comment by parkervcp** [comment]
@mikroskeem Can you try that out and let me know how it works for you?

**Comment by parkervcp** [comment]
I didn't mean to merge that in.
