### ISSUE TITLE
Pagination deserialization error

### ISSUE THREAD

**Issue by mikroskeem** [parkervcp/crocgodyl#2]
Reproducing:
```go
	if servers, err := crocgodyl.GetServers(); err == nil {
		for server := range servers.Server {
			zap.L().Info("found server", zap.Reflect("server", server))
		}
	} else {
		zap.L().Fatal("failed to communicate with the panel", zap.Error(err))
	}
```

And you should get error:
`json: cannot unmarshal array into Go struct field Pagination.meta.pagination.links of type crocgodyl.Links`

**Comment by parkervcp** [comment]
Can you do this with the standard logging library please. I want it to be reproducible without needing to write other things around it.

Thanks. I will still look into it.

**Comment by mikroskeem** [comment]
```go
	if servers, err := crocgodyl.GetServers(); err == nil {
		for server := range servers.Server {
			log.Printf("found server %v", server)
		}
	} else {
		log.Printf("failed to communicate with the panel: %s", err)
	}
```

There you go.

**Comment by parkervcp** [comment]
So the way I would write this is as follows. I assume this is doing that you wanted?

```
	servers, err := croc.GetServers()
	if err != nil {
		log.Printf("failed to communicate with the panel: %s", err)
	}

	for _, server := range servers.Server {
		log.Printf("found server %+v", server)
	}
```

In your for loop the `server` you are getting ranging over the `servers.Server` is a bool and not a `server` object.

**Comment by mikroskeem** [comment]
Nice catch (I made a typo when I was making this small snippet), however that's not the main issue here. `json: cannot unmarshal array into Go struct field Pagination.meta.pagination.links of type crocgodyl.Links` still pops up when I query my Pterodactyl instance.

Pterodactyl version is latest - 0.7.15. Forgot to add this information at first place.

**Comment by parkervcp** [comment]
Did you try to re-organize it in the way I wrote it?

I know you are trying to write a if catch statement but I want to be sure.

Also this requires an application api token not a user api token. Just to be sure.

**Comment by mikroskeem** [comment]
```
2019/12/06 06:13:56 failed to communicate with the panel: json: cannot unmarshal array into Go struct field Pagination.meta.pagination.links of type crocgodyl.Links
2019/12/06 06:13:56 found server {Object:server Attributes:{ID:.. ExternalID:<nil> UUID:... Identifier:... Name:...}
```

Issue still persists.

**Comment by parkervcp** [comment]
Code block please. So I can test it locally. I will continue looking at this tomorrow FYI.

**Comment by mikroskeem** [comment]
Literally the last code block you pasted here, except `croc` -> `crocgodyl` and `crocgodyl.New("panel url", "", "key")` added.

**Comment by parkervcp** [comment]
I am using the example I have in the repo.

I have pared it down to these - https://gist.github.com/parkervcp/c312283e1378338598d7f54865cf35a7

I think it's due to the way you are trying to use a multivalue. The if block you are using should be used with `recover()`.

**Comment by mikroskeem** [comment]
So you're saying I should ignore the error instead and carry on? Well, the issue can be closed then, and in conclusion I wasted my time 😄

**Comment by parkervcp** [comment]
I'm not ignoring the error. I'm saying the way you are trying to catch it is causing the error.

I have never seen someone try to wrap it like that to catch an error.

**Comment by mikroskeem** [comment]
The way I catch the error is not the issue here really. What I'm trying to point out is that the library itself returns an error when you call `GetServers`. (scroll into end for TL;DR;)

It's usually a good practice to check for an error, and if there actually is an error then ignore the result.

[The code you sent before](https://github.com/parkervcp/crocgodyl/issues/2#issuecomment-562423263) does not do that, and as you can see then [I get both error and response](https://github.com/parkervcp/crocgodyl/issues/2#issuecomment-562425329) using it. As json does not quite fit into the structs what are defined in the code in this repository, then I'm running into [UnmarshalTypeError](https://golang.org/pkg/encoding/json/#UnmarshalTypeError)

>The if block you are using should be used with recover().

... what? why? It's not a panic

>I think it's due to the way you are trying to use a multivalue

That does not make sense at all. Golang is not lazily evaluated language, json does not get deserialized at point when I ask it to be printed out, it gets deserialized eagerly at the point when [body is received fully](https://github.com/parkervcp/crocgodyl/blob/master/appServer.go#L136) and put into variables, what I check in my code. Printf does not (and cannot) trigger this.

> I have never seen someone try to wrap it like that to catch an error.

What is the logical difference between those two cases (pseudocode):
```
if err := nil; err == nil {
    print("success")
} else {
    print("fail")
}
```

and

```
if err := nil; err != nil {
    print("fail")
} else {
    print("success")
}
```

There is no difference besides ordering and equals check being different (even though doing the same thing).

Back to the error topic. Of course I can check if the error is `UnmarshalTypeError` and ignore it, but ideally the structs should be checked against current Pterodactyl API, so that this error would not appear again.

**Comment by parkervcp** [comment]
I'm not ignoring the error.

I set servers and err using GetServers. I then check is the err is not nil. Then I run the for loop.

Sure it uses more lines but is more readable and doesn't fail.

**Comment by parkervcp** [comment]
So looking at it again I am seeing the error. I am also still able to get the info you wanted out of it.

The error was crammed in with the other stuff I was printing out so I was missing it.

![image](https://user-images.githubusercontent.com/1207679/70319019-4629f980-17ef-11ea-84d8-02480e5ff0e1.png)

**Comment by parkervcp** [comment]
This is also proof that I need to not look at these right before going to bed.

I apologize for that. Please check the PR I made @mikroskeem
